<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>UsbDeviceActivity.Protocol</AssemblyName>
    <RootNamespace>UsbDeviceActivity</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Common\ReliableProtocolFile.cs" Link="ReliableProtocolFile.cs" />
  </ItemGroup>
</Project>
