<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>HashAlgorithms.Behavior</AssemblyName>
    <RootNamespace>HashAlgorithms</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HashAlgorithms.Protocol\HashAlgorithms.Protocol.csproj" />
  </ItemGroup>
</Project>
