<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>NetworkActivity.Behavior</AssemblyName>
    <RootNamespace>NetworkActivity</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NetworkActivity.Protocol\NetworkActivity.Protocol.csproj" />
  </ItemGroup>
</Project>
