<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ServiceActivity.Protocol</AssemblyName>
    <RootNamespace>ServiceActivity</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Common\ReliableProtocolFile.cs" Link="ReliableProtocolFile.cs" />
  </ItemGroup>
</Project>
